name: Deploy

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-northeast-1
  AWS_ROLE_ARN: arn:aws:iam::203369940478:role/my-blog-github-actions-deploy-role
  S3_BUCKET: jishinzerogon-dev-frontend
  CLOUDFRONT_DISTRIBUTION_ID: ""

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: コードを取得
        uses: actions/checkout@v6

      - name: Node.js セットアップ
        uses: actions/setup-node@v5
        with:
          node-version: "22"
          cache: "npm"

      - name: 依存関係をインストール
        run: npm ci

      - name: フロントエンドをビルド
        run: npm run build

      - name: AWS認証情報を設定 (OIDC)
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: S3 に同期
        run: |
          aws s3 sync dist/ s3://$S3_BUCKET/ --delete

      - name: CloudFront キャッシュを無効化
        run: |
          aws cloudfront create-invalidation \
            --distribution-id $E2PJGY8HMFUV66 \
            --paths "/*"
