name: Terraform CI

on:
  pull_request:
    branches:
      - main
    paths:
      - "terraform/**"

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-northeast-1
  AWS_ROLE_ARN: arn:aws:iam::203369940478:role/my-blog-github-actions-plan-role
  TF_WORKING_DIR: terraform

jobs:
  check:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}

    steps:
      - name: コードを取得
        uses: actions/checkout@v6

      - name: Terraformをセットアップ
        uses: hashicorp/setup-terraform@v3

      - name: terraform fmt
        run: terraform fmt -check

      - name: AWS認証情報を設定 (OIDC)
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: terraform init
        run: terraform init

      - name: terraform validate
        run: terraform validate

      - name: terraform plan
        run: terraform plan -no-color
